### ISSUE TITLE
Addon Export: Invalid character

### ISSUE THREAD

**Issue by listefano** [WowUp/WowUp#1046]
**Describe the bug**
Trying to export my addon information only results in the following screen. In the "renderer.log" I found the following error message: 
[2021-11-05 14:56:10.208] [error] Caught error InvalidCharacterError: Invalid character
    at __node_internal_ (node:internal/util:449:10)
    at btoa (node:buffer:1219:13)
    at t.ngOnInit (file:///C:/Users/stefan/AppData/Local/Programs/wowup/resources/app.asar/dist/main.d1c8535db84819c29372.js:7:1595756)
    at yg (file:///C:/Users/stefan/AppData/Local/Programs/wowup/resources/app.asar/dist/main.d1c8535db84819c29372.js:7:487320)
    at i6 (file:///C:/Users/stefan/AppData/Local/Programs/wowup/resources/app.asar/dist/main.d1c8535db84819c29372.js:7:487151)
    at tp (file:///C:/Users/stefan/AppData/Local/Programs/wowup/resources/app.asar/dist/main.d1c8535db84819c29372.js:7:486871)
    at ph (file:///C:/Users/stefan/AppData/Local/Programs/wowup/resources/app.asar/dist/main.d1c8535db84819c29372.js:7:514626)
    at file:///C:/Users/stefan/AppData/Local/Programs/wowup/resources/app.asar/dist/main.d1c8535db84819c29372.js:7:514919
    at ph (file:///C:/Users/stefan/AppData/Local/Programs/wowup/resources/app.asar/dist/main.d1c8535db84819c29372.js:7:514944)
    at L_ (file:///C:/Users/stefan/AppData/Local/Programs/wowup/resources/app.asar/dist/main.d1c8535db84819c29372.js:7:521601)

**To Reproduce**
1. Open the menu to export addons
2. Click on "Import/Export Addons"

**Expected behavior**
I get the addon export data. 

**Screenshots**
![image](https://user-images.githubusercontent.com/14946911/140521986-82c6d391-8372-4d65-966a-f0611a92f83d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (Version 21H1, Build: 19043.1288)

**Additional context**
List of currently installed addons: 
- ALL THE THINGS
- AddOnSkins
- AddOns CPU Usage
- AdvancedInterfaceOptions
- ArkInventory
- BigWigs Bossmods
- BigWigs_BattleForAzeroth
- BigWigs_BurningCrusade
- BigWigs_Cataclysm
- BigWigs_Classic
- BigWigs_Legion
- BigWigs_MistsOfPandaria
- BigWigs_WarlordsOfDraenor
- BigWigs_WrathOfTheLichKing
- BtWQuests
- BtWQuests: Battle for Azeroth
- BtWQuests: Cataclysm
- BtWQuests: Legion
- BtWQuests: Mists of Pandaria
- BtWQuests: Shadowlands
- BtWQuests: The Burning Crusade
- BtWQuests: Warlords of Draenor
- BtWQuests: Wrath of the Lich King
- BugGrabber
- BugSack
- BuyEmAll Shadowlands
- Can I Mog It?
- Details! Damage Meter
- ElvUI
- FarmHud
- FriendGroups
- GTFO
- Garrison Mission Manager
- GatherMate2
- GatherMate2_Data
- GroupfinderFlags
- HandyNotes
- HandyNotes: Shadowlands
- LittleWigs
- Maze Helper (Mists of Tirna Scithe)
- Method Raid Tools
- Mythic Dungeon Tools
- Narcissus
- OPie
- OPie​
- OmniCD
- Plater Nameplates
- Raider.IO Mythic Plus and Raiding
- Routes
- Routes Import/Export
- SavedInstances
- Shadow & Light (ElvUI Plugin)
- SharedMedia
- SharedMedia_Causese
- Simulationcraft
- TomTom
- TradeSkillMaster
- TradeSkillMaster_AppHelper
- Venture Plan
- WeakAuras
- WeakAuras Companion
- World Quests List

**Comment by jliddev** [comment]
Can you go one folder up from the logs folder and attach your addons.json file?

**Comment by listefano** [comment]
Sure, no problem. Because some limitations from github I was not able to directly attach the "addons.json" and had to rename the file to "addons.txt". 
[addons.txt](https://github.com/WowUp/WowUp/files/7486817/addons.txt)

**Comment by jliddev** [comment]
This should hopefully be resolved with the latest 2.5.1 release

**Comment by listefano** [comment]
Can confirm, the bug is resolved with the 2.5.1 release. Thanks :)
