### ISSUE TITLE
Error: Failed to get client location key: 1, Classic

### ISSUE THREAD

**Issue by linaori** [WowUp/WowUp#1055]
Occasionally I see this error come by in people's logs. Might be worth investigating to see what impact this could have.

```
[2021-11-15 13:16:29.075] [error] Error: Failed to get client location key: 1, Classic
    at t.getLegacyClientLocationKey (file:///C:/Users/<user>/AppData/Local/Programs/wowup/resources/app.asar/dist/main.d0ac002e798bbb309e11.js:7:1178606)
    at file:///C:/Users/<user>/AppData/Local/Programs/wowup/resources/app.asar/dist/main.d0ac002e798bbb309e11.js:7:1184758
    at Generator.next (<anonymous>)
    at AN (file:///C:/Users/<user>/AppData/Local/Programs/wowup/resources/app.asar/dist/main.d0ac002e798bbb309e11.js:7:638229)
    at h (file:///C:/Users/<user>/AppData/Local/Programs/wowup/resources/app.asar/dist/main.d0ac002e798bbb309e11.js:7:638432)
    at file:///C:/Users/<user>/AppData/Local/Programs/wowup/resources/app.asar/dist/main.d0ac002e798bbb309e11.js:7:638493
    at new t (file:///C:/Users/<user>/AppData/Local/Programs/wowup/resources/app.asar/dist/polyfills.5d4af3666655c9d9bc6c.js:1:17776)
    at file:///C:/Users/<user>/AppData/Local/Programs/wowup/resources/app.asar/dist/main.d0ac002e798bbb309e11.js:7:638373
    at t.migrateLegacyInstallations (file:///C:/Users/<user>/AppData/Local/Programs/wowup/resources/app.asar/dist/main.d0ac002e798bbb309e11.js:7:1185351)
    at file:///C:/Users/<user>/AppData/Local/Programs/wowup/resources/app.asar/dist/main.d0ac002e798bbb309e11.js:7:1184416
[2021-11-15 13:16:29.077] [info]  Legacy installation addons finished
```

**Comment by jliddev** [comment]
This should have no impact, it was only used for people upgrading to the new way we store installations. should probably be a warning or removed at this point.
