### ISSUE TITLE
WowUp AppImage fails to run on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by dominic-jones** [WowUp/WowUp#1275]
**Describe the bug**
Run WowUp via AppImage on Ubuntu. Fails to start up. Running from the command line, I get an electron error.

```js
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ElectronStore.Conf._deserialize (/tmp/.mount_WowUp-L5Vtl9/resources/app.asar/node_modules/conf/dist/source/index.js:67:43)
    at ElectronStore.get store [as store] (/tmp/.mount_WowUp-L5Vtl9/resources/app.asar/node_modules/conf/dist/source/index.js:278:43)
    at new Conf (/tmp/.mount_WowUp-L5Vtl9/resources/app.asar/node_modules/conf/dist/source/index.js:131:32)
    at new ElectronStore (/tmp/.mount_WowUp-L5Vtl9/resources/app.asar/node_modules/electron-store/index.js:69:3)
    at Object.<anonymous> (/tmp/.mount_WowUp-L5Vtl9/resources/app.asar/app/stores.js:7:22)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
```

**To Reproduce**
Simply run WowUp on latest Ubuntu LTS

**Desktop (please complete the following information):**
 - OS: PopOS variant of Ubuntu
```
Distributor ID:	Pop
Description:	Pop!_OS 22.04 LTS
Release:	22.04
Codename:	jammy
```
 - Browser: AppImage so.. electron I guess?
 - Version: Been broken for a few versions, but tested on the latest: `WowUp-2.8.3-beta.4`

**Additional context**
Possibly similar to https://github.com/WowUp/WowUp/issues/1274 but since I'm on a different OS I reported it separately.

**Comment by jliddev** [comment]
Give this a try on the latest beta 
https://github.com/WowUp/WowUp/releases/tag/v2.8.3-beta.6
