### ISSUE TITLE
ERROR.ASSET_NOT_FOUND importing a github repo

### ISSUE THREAD

**Issue by FREEZEball** [WowUp/WowUp#1321]
**Describe the bug**
An error window with no useful information appears while trying to import specific repo from Github.

**To Reproduce**
1. Go to 'Get Add-ons'
2. Click on 'Install from URL'
3. Paste link to [this](url=https://github.com/ItsJustMeChris/idTip-Community-Fork) Github repo.
![image](https://user-images.githubusercontent.com/11259935/198711211-153c510c-b4c0-4731-9eea-7e3658cbb97e.png)
4. Click 'Import'
5. See error:
![image](https://user-images.githubusercontent.com/11259935/198711574-49ad2f49-9b7a-4da9-b89b-ea7aeb2dc77a.png)
5.a Logs do not show anything either:
```
% wowup -v

21:46:33.299 › Main starting
21:46:33.301 › Electron: 20.1.0
21:46:33.301 › BinaryPath: /usr/lib/wowup/wowup
21:46:33.302 › ExecPath /usr/lib/wowup/wowup
21:46:33.302 › Args [ '/usr/lib/wowup/wowup', '-v' ]
21:46:33.303 › Log path: /home/fb/.config/WowUp/logs
21:46:33.304 › ARGV { _: [], serve: false, hidden: false, v: true }
21:46:33.304 › USER_AGENT WowUp-Client/2.9.0 (Linux; 6.0.2-zen1-1-zen; x64;  +https://wowup.io)
21:46:33.559 › Hardware acceleration enabled
21:46:33.599 › App ready: 296ms
21:46:33.632 › process.versions {
  node: '16.15.0',
  v8: '10.4.132.22-electron.0',
  uv: '1.43.0',
  zlib: '1.2.12',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '107',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1',
  cldr: '41.0',
  icu: '71.1',
  tz: '2022a',
  unicode: '14.0',
  electron: '20.1.0',
  chrome: '104.0.5112.102'
}
21:46:33.633 › Loading app URL: 330ms
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
21:46:33.652 › window config saved
21:46:33.823 › APPIMAGE env is not defined, current application is not an AppImage
21:46:33.823 › checkForUpdates null
21:46:34.039 › [CreateDirectory] '/home/fb/.config/WowUp/downloads'
Creating tray
21:46:34.187 › will-attach-webview
21:46:34.379 › [wago-preload] init https://addons.wago.io/wowup_ad
21:46:34.585 › [wago-preload] wago manual key extraction
[360426:1028/214644.785914:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[360426:1028/214656.924048:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[360426:1028/214701.297970:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```

**Expected behavior**
A dialog window confirming to import the add-on appears.

**Desktop (please complete the following information):**
 - OS: archlinux
 - Browser firefox
 - Version 2.9.0 (latest as of today), installed through AUR

**Additional context**
Previously, even if repositories contained incompatible releases of add-ons, the app clearly told the user so. This error message contains no useful information.

**Comment by FREEZEball** [comment]
Ah, if it makes any difference, I **am** using Github access token.

**Comment by Tyarum** [comment]
I am having the same issue, so to add information, I am seeing the same issues while not using an access token.
Additional repositories with issues for me [LibGetFrame](https://github.com/mrbuds/LibGetFrame) and [Mythic Dungeon Tools](https://github.com/Nnoggie/MythicDungeonTools/releases)

There is also nothing in the main log, however the renderer log has the following:

```
[2022-10-29 16:39:55.618] [info]  [GET] https://api.github.com/repos/mrbuds/LibGetFrame/releases 200 346ms
[2022-10-29 16:39:55.618] [info]  searchByUrl result {
  release: {
    url: 'https://api.github.com/repos/mrbuds/LibGetFrame/releases/67152810',
    assets_url: 'https://api.github.com/repos/mrbuds/LibGetFrame/releases/67152810/assets',
    upload_url: 'https://uploads.github.com/repos/mrbuds/LibGetFrame/releases/67152810/assets{?name,label}',
    html_url: 'https://github.com/mrbuds/LibGetFrame/releases/tag/1.5.10',
    id: 67152810,
    author: {
      login: 'mrbuds',
      id: 189656,
      node_id: 'MDQ6VXNlcjE4OTY1Ng==',
      avatar_url: 'https://avatars.githubusercontent.com/u/189656?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/mrbuds',
      html_url: 'https://github.com/mrbuds',
      followers_url: 'https://api.github.com/users/mrbuds/followers',
      following_url: 'https://api.github.com/users/mrbuds/following{/other_user}',
      gists_url: 'https://api.github.com/users/mrbuds/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/mrbuds/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/mrbuds/subscriptions',
      organizations_url: 'https://api.github.com/users/mrbuds/orgs',
      repos_url: 'https://api.github.com/users/mrbuds/repos',
      events_url: 'https://api.github.com/users/mrbuds/events{/privacy}',
      received_events_url: 'https://api.github.com/users/mrbuds/received_events',
      type: 'User',
      site_admin: false
    },
    node_id: 'RE_kwDOCcJG084EAKuq',
    tag_name: '1.5.10',
    target_commitish: 'master',
    name: '1.5.10',
    draft: false,
    prerelease: false,
    created_at: '2022-05-18T08:49:27Z',
    published_at: '2022-05-18T08:52:52Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/mrbuds/LibGetFrame/tarball/1.5.10',
    zipball_url: 'https://api.github.com/repos/mrbuds/LibGetFrame/zipball/1.5.10',
    body: ''
  }
}
[2022-10-29 16:39:55.619] [error] searchByUrl failed UM: https://github.com/mrbuds/LibGetFrame
    at file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/main.7447cb6b97189718.js:1:2219322
    at Generator.next (<anonymous>)
    at wR (file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/main.7447cb6b97189718.js:1:1681783)
    at h (file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/main.7447cb6b97189718.js:1:1681986)
    at v.invoke (file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/polyfills.bd3495e97b213c56.js:1:6543)
    at Object.onInvoke (file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/main.7447cb6b97189718.js:1:1613475)
    at v.invoke (file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/polyfills.bd3495e97b213c56.js:1:6483)
    at M.run (file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/polyfills.bd3495e97b213c56.js:1:1939)
    at file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/polyfills.bd3495e97b213c56.js:1:16738
    at v.invokeTask (file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/polyfills.bd3495e97b213c56.js:1:7161)
[2022-10-29 16:39:55.619] [error] UM: https://github.com/mrbuds/LibGetFrame
    at file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/main.7447cb6b97189718.js:1:2219322
    at Generator.next (<anonymous>)
    at wR (file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/main.7447cb6b97189718.js:1:1681783)
    at h (file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/main.7447cb6b97189718.js:1:1681986)
    at v.invoke (file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/polyfills.bd3495e97b213c56.js:1:6543)
    at Object.onInvoke (file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/main.7447cb6b97189718.js:1:1613475)
    at v.invoke (file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/polyfills.bd3495e97b213c56.js:1:6483)
    at M.run (file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/polyfills.bd3495e97b213c56.js:1:1939)
    at file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/polyfills.bd3495e97b213c56.js:1:16738
    at v.invokeTask (file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/polyfills.bd3495e97b213c56.js:1:7161)
[2022-10-29 16:39:57.355] [info]  The dialog was closed
[2022-10-29 16:40:35.261] [info]  [GET] https://api.github.com/repos/Nnoggie/MythicDungeonTools/releases 200 489ms
[2022-10-29 16:40:35.261] [info]  searchByUrl result {
  release: {
    url: 'https://api.github.com/repos/Nnoggie/MythicDungeonTools/releases/80948925',
    assets_url: 'https://api.github.com/repos/Nnoggie/MythicDungeonTools/releases/80948925/assets',
    upload_url: 'https://uploads.github.com/repos/Nnoggie/MythicDungeonTools/releases/80948925/assets{?name,label}',
    html_url: 'https://github.com/Nnoggie/MythicDungeonTools/releases/tag/v4.0.1.1',
    id: 80948925,
    author: {
      login: 'Nnoggie',
      id: 27819512,
      node_id: 'MDQ6VXNlcjI3ODE5NTEy',
      avatar_url: 'https://avatars.githubusercontent.com/u/27819512?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Nnoggie',
      html_url: 'https://github.com/Nnoggie',
      followers_url: 'https://api.github.com/users/Nnoggie/followers',
      following_url: 'https://api.github.com/users/Nnoggie/following{/other_user}',
      gists_url: 'https://api.github.com/users/Nnoggie/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Nnoggie/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Nnoggie/subscriptions',
      organizations_url: 'https://api.github.com/users/Nnoggie/orgs',
      repos_url: 'https://api.github.com/users/Nnoggie/repos',
      events_url: 'https://api.github.com/users/Nnoggie/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Nnoggie/received_events',
      type: 'User',
      site_admin: false
    },
    node_id: 'RE_kwDOB1Ar184E0y69',
    tag_name: 'v4.0.1.1',
    target_commitish: 'master',
    name: 'v4.0.1.1',
    draft: false,
    prerelease: false,
    created_at: '2022-10-25T16:34:51Z',
    published_at: '2022-10-25T16:35:57Z',
    assets: [],
    tarball_url: 'https://api.github.com/repos/Nnoggie/MythicDungeonTools/tarball/v4.0.1.1',
    zipball_url: 'https://api.github.com/repos/Nnoggie/MythicDungeonTools/zipball/v4.0.1.1',
    body: 'Download MDT only at https://www.curseforge.com/wow/addons/mythic-dungeon-tools. This release is for packaging purposes only!'
  }
}
[2022-10-29 16:40:35.262] [error] searchByUrl failed UM: https://github.com/Nnoggie/MythicDungeonTools/releases
    at file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/main.7447cb6b97189718.js:1:2219322
    at Generator.next (<anonymous>)
    at wR (file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/main.7447cb6b97189718.js:1:1681783)
    at h (file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/main.7447cb6b97189718.js:1:1681986)
    at v.invoke (file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/polyfills.bd3495e97b213c56.js:1:6543)
    at Object.onInvoke (file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/main.7447cb6b97189718.js:1:1613475)
    at v.invoke (file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/polyfills.bd3495e97b213c56.js:1:6483)
    at M.run (file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/polyfills.bd3495e97b213c56.js:1:1939)
    at file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/polyfills.bd3495e97b213c56.js:1:16738
    at v.invokeTask (file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/polyfills.bd3495e97b213c56.js:1:7161)
[2022-10-29 16:40:35.267] [error] UM: https://github.com/Nnoggie/MythicDungeonTools/releases
    at file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/main.7447cb6b97189718.js:1:2219322
    at Generator.next (<anonymous>)
    at wR (file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/main.7447cb6b97189718.js:1:1681783)
    at h (file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/main.7447cb6b97189718.js:1:1681986)
    at v.invoke (file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/polyfills.bd3495e97b213c56.js:1:6543)
    at Object.onInvoke (file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/main.7447cb6b97189718.js:1:1613475)
    at v.invoke (file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/polyfills.bd3495e97b213c56.js:1:6483)
    at M.run (file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/polyfills.bd3495e97b213c56.js:1:1939)
    at file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/polyfills.bd3495e97b213c56.js:1:16738
    at v.invokeTask (file:///C:/Users/MyName/AppData/Local/Programs/wowup/resources/app.asar/dist/polyfills.bd3495e97b213c56.js:1:7161)
[2022-10-29 16:40:37.940] [info]  The dialog was closed
```
Which includes the following line from Mythic Dungeon Tools
```Download MDT only at https://www.curseforge.com/wow/addons/mythic-dungeon-tools. This release is for packaging purposes only!```
Suggesting the releases may not support downloading this way.

For completeness, OS Windows 10.0.19044, Browser: N/A, WowUp 2.9.0

**Comment by jondeans** [comment]
The error is 100% not clear what the issue is, but @Tyarum has a good explanation. It does seem like the packages need to have a proper release with a `release.json` as part of the Assets.

[BetterWardrobe](https://github.com/SLOKnightfall/BetterWardrobe) was failing a few days ago but they set up a proper release and now it's working great.
