### ISSUE TITLE
Wago/Github changelog not showing up in WowUp

### ISSUE THREAD

**Issue by InvisiBilldotnet** [WowUp/WowUp#1347]
**Describe the bug**
WowUp shows "No changelog available" but Wago has a changelog in the file's release notes.

**To Reproduce**
1. Click on a Wago addon and view its Changelog tab to see "No changelog available"
2. Follow "View on Wago" link to view the file's actual Changelog content.

**Expected behavior**
Changelog tab should match Wago release notes.

**Screenshots**
![image](https://user-images.githubusercontent.com/21955683/202013531-9998fc49-e0de-4e08-9a95-b32f4ad5d937.png)
![image](https://user-images.githubusercontent.com/21955683/202013566-43e5991c-0f8c-4b44-a8f3-9a134a176a4e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H2
 - WowUp 2.9.1

**Additional context**
GitHub may have the same behavior too.  WowI seems to be functioning properly.

**Comment by jliddev** [comment]
Appears to work as expected here, perhaps there is some error in your logs 
![image](https://user-images.githubusercontent.com/20467484/202581436-41a93be1-ec1d-4435-a33c-5f9e5eaf6d80.png)

**Comment by InvisiBilldotnet** [comment]
With no changes on my end, it seemed to be working earlier, but now it's not again.  I did find something in the logs that seems to relate to the issue, but it's not obvious what/if I can personally do about it.

```
[2022-11-17 18:33:16.252] [error] [wago] Failed to get changelog Error: [wago] circuit breaker is open
    at Fxe.ensureToken (file:///C:/Users/<USERNAME>/AppData/Local/Programs/wowup/resources/app.asar/dist/main.32aacaf1373d09af.js:1:1217911)
    at file:///C:/Users/<USERNAME>/AppData/Local/Programs/wowup/resources/app.asar/dist/main.32aacaf1373d09af.js:1:1214395
    at Generator.next (<anonymous>)
    at sW (file:///C:/Users/<USERNAME>/AppData/Local/Programs/wowup/resources/app.asar/dist/main.32aacaf1373d09af.js:1:635470)
    at a (file:///C:/Users/<USERNAME>/AppData/Local/Programs/wowup/resources/app.asar/dist/main.32aacaf1373d09af.js:1:635673)
    at file:///C:/Users/<USERNAME>/AppData/Local/Programs/wowup/resources/app.asar/dist/main.32aacaf1373d09af.js:1:635734
    at new t (file:///C:/Users/<USERNAME>/AppData/Local/Programs/wowup/resources/app.asar/dist/polyfills.bd3495e97b213c56.js:1:18319)
    at file:///C:/Users/<USERNAME>/AppData/Local/Programs/wowup/resources/app.asar/dist/main.32aacaf1373d09af.js:1:635614
    at Fxe.getAddonById (file:///C:/Users/<USERNAME>/AppData/Local/Programs/wowup/resources/app.asar/dist/main.32aacaf1373d09af.js:1:1214610)
    at file:///C:/Users/<USERNAME>/AppData/Local/Programs/wowup/resources/app.asar/dist/main.32aacaf1373d09af.js:1:1212798
[2022-11-17 18:33:16.252] [error] [wago] failed to get description Error: [wago] circuit breaker is open
    at Fxe.ensureToken (file:///C:/Users/<USERNAME>/AppData/Local/Programs/wowup/resources/app.asar/dist/main.32aacaf1373d09af.js:1:1217911)
    at file:///C:/Users/<USERNAME>/AppData/Local/Programs/wowup/resources/app.asar/dist/main.32aacaf1373d09af.js:1:1214395
    at Generator.next (<anonymous>)
    at sW (file:///C:/Users/<USERNAME>/AppData/Local/Programs/wowup/resources/app.asar/dist/main.32aacaf1373d09af.js:1:635470)
    at a (file:///C:/Users/<USERNAME>/AppData/Local/Programs/wowup/resources/app.asar/dist/main.32aacaf1373d09af.js:1:635673)
    at file:///C:/Users/<USERNAME>/AppData/Local/Programs/wowup/resources/app.asar/dist/main.32aacaf1373d09af.js:1:635734
    at new t (file:///C:/Users/<USERNAME>/AppData/Local/Programs/wowup/resources/app.asar/dist/polyfills.bd3495e97b213c56.js:1:18319)
    at file:///C:/Users/<USERNAME>/AppData/Local/Programs/wowup/resources/app.asar/dist/main.32aacaf1373d09af.js:1:635614
    at Fxe.getAddonById (file:///C:/Users/<USERNAME>/AppData/Local/Programs/wowup/resources/app.asar/dist/main.32aacaf1373d09af.js:1:1214610)
    at file:///C:/Users/<USERNAME>/AppData/Local/Programs/wowup/resources/app.asar/dist/main.32aacaf1373d09af.js:1:1212579
```

**Comment by jliddev** [comment]
I would guess its one of those weird wago token expired issues. will see what i can do.

**Comment by InvisiBilldotnet** [comment]
Here's a renderer log for MBB 4.0.17 on GitHub.  It shows the correct changelog data in `latestChangelog` but an older version number in `latestChangelogVersion`.  Not sure if that might be causing problems.  Nothing else looks obviously wrong to me.

![image](https://user-images.githubusercontent.com/21955683/202799959-b4cfd183-4141-427e-9e1c-c89806b7b28a.png)

![image](https://user-images.githubusercontent.com/21955683/202800415-0f78a231-ab8f-45d5-8f3b-0e112d222dce.png)

```
[2022-11-18 15:42:50.345] [info]  Checking for addon updates...
[2022-11-18 15:45:34.697] [info]  model {
  listItem: {
    installState: 6,
    isInstalling: false,
    installProgress: 0,
    stateTextTranslationKey: 'COMMON.ADDON_STATE.UPDATE',
    selected: false,
    releasedAt: 1668800801000,
    installedAt: 1667952749871,
    isLoadOnDemand: false,
    hasThumbnail: true,
    thumbnailLetter: 'M',
    canonicalName: 'mbb',
    addon: {
      id: 'c784ee5d-34cf-4983-8f6f-ab6961e90894',
      name: 'MBB',
      thumbnailUrl: 'https://avatars.githubusercontent.com/u/19942228?v=4',
      latestVersion: 'MBB-4.0.17-release.zip',
      clientType: 0,
      externalId: 'pereira-a/MBB',
      gameVersion: '10.0.0',
      author: 'pereira-a',
      downloadUrl: 'https://github.com/pereira-a/MBB/releases/download/4.0.17-release/MBB-4.0.17-release.zip',
      externalUrl: 'https://github.com/pereira-a/MBB',
      providerName: 'GitHub',
      channelType: 0,
      isIgnored: false,
      autoUpdateEnabled: false,
      autoUpdateNotificationsEnabled: false,
      releasedAt: '2022-11-18T19:46:41.000Z',
      dependencies: [],
      externalChannel: 'Stable',
      isLoadOnDemand: false,
      fundingLinks: [],
      latestChangelogVersion: 'MBB-4.0.10-release.zip',
      installationId: '91f49ee6-d3d4-4402-bc9b-4aa0f6b5530f',
      installedFolderList: [ 'MBB' ],
      installedVersion: 'MBB-4.0.16-release.zip',
      installedAt: '2022-11-09T00:12:29.871Z',
      installedFolders: 'MBB',
      externalIds: [ { id: 'pereira-a/MBB', providerName: 'GitHub' } ],
      summary: 'A Retail WoW addon that gathers all minimap addon buttons into one button',
      latestChangelog: '<h2>Commits</h2><ul><li>bdb386b: Update MBB.toc (Axel Clifford) <a href="https://github.com/pereira-a/MBB/pull/24">#24</a></li><li>d15328a: increase version (pereira-a)</li></ul>'
    }
  }
}
```

**Comment by InvisiBilldotnet** [comment]
Here's another example of a Github changelog not showing when the data appears in the renderer log.  I have 10.2-001 installed, and 10.2-002 is available to download.  Once again, latestChangelogVersion shows an older version, 10.1-016 from June in this case (there have been 11 releases since then).

```
[2023-11-10 08:36:10.115] [info]  model {
  listItem: {
    installState: 7,
    isInstalling: false,
    installProgress: 0,
    stateTextTranslationKey: 'COMMON.ADDON_STATE.UPDATE',
    selected: false,
    releasedAt: 1699616157000,
    installedAt: 1699451581814,
    isLoadOnDemand: false,
    hasThumbnail: true,
    thumbnailLetter: 'M',
    canonicalName: 'manuscriptsjournal',
    addon: {
      id: '86e0c31a-f1ec-45dc-9336-b17856be8c78',
      name: 'ManuscriptsJournal',
      thumbnailUrl: 'https://avatars.githubusercontent.com/u/105718850?v=4',
      latestVersion: 'ManuscriptsJournal-10.2-002.zip',
      clientType: 0,
      externalId: 'TLDRMissions/ManuscriptsJournal',
      gameVersion: '10.2.0',
      author: 'TLDRMissions',
      downloadUrl: 'https://api.github.com/repos/TLDRMissions/ManuscriptsJournal/releases/assets/134894245',
      externalUrl: 'https://github.com/TLDRMissions/ManuscriptsJournal',
      providerName: 'GitHub',
      channelType: 0,
      isIgnored: false,
      autoUpdateEnabled: false,
      autoUpdateNotificationsEnabled: false,
      releasedAt: '2023-11-10T11:35:57.000Z',
      dependencies: [],
      externalChannel: 'Stable',
      isLoadOnDemand: false,
      fundingLinks: [],
      latestChangelogVersion: 'ManuscriptsJournal-10.1-016.zip',
      installationId: '91f49ee6-d3d4-4402-bc9b-4aa0f6b5530f',
      installedFolderList: [ 'ManuscriptsJournal' ],
      installedVersion: 'ManuscriptsJournal-10.2-001.zip',
      installedAt: '2023-11-08T13:53:01.814Z',
      installedFolders: 'ManuscriptsJournal',
      externalIds: [
        {
          id: 'TLDRMissions/ManuscriptsJournal',
          providerName: 'GitHub'
        }
      ],
      summary: null,
      latestChangelog: '<h1>Manuscripts Journal</h1><h2><a href="https://github.com/TLDRMissions/ManuscriptsJournal/tree/10.2-002">10.2-002</a> (2023-11-10)</h2><p><a href="https://github.com/TLDRMissions/ManuscriptsJournal/compare/10.2-001...10.2-002">Full Changelog</a> <a href="https://github.com/TLDRMissions/ManuscriptsJournal/releases">Previous Releases</a></p><ul><li>Update to latest known sources in 10.2</li><li>Bugfix for #22<br>Closes: https://github.com/TLDRMissions/ManuscriptsJournal/issues/22</li></ul>'
    }
  }
}
```
