### ISSUE TITLE
External links no longer work

### ISSUE THREAD

**Issue by linaori** [WowUp/WowUp#1440]
Clicking many of the links that lead to an external location no longer function. Version: 2.9.4-beta2. Several still do, such as the link to wago in the "why am I seeing this ad", and links in the News section.
![image](https://github.com/WowUp/WowUp/assets/1754678/8fd55523-daef-4f2d-9fe5-9794aa4474b0)
![image](https://github.com/WowUp/WowUp/assets/1754678/bd5a27a4-b203-4581-8a42-bc74ac3b29be)

```
lyfills.6a4fafe69005f56d.js:1 10:00:25.312 › Caught error TypeError: Cannot read properties of undefined (reading 'href')
    at A0.onClick (main.46c4670f1ad553ac.js:1:1614443)
    at main.46c4670f1ad553ac.js:1:1614692
    at v (main.46c4670f1ad553ac.js:1:621150)
    at r (main.46c4670f1ad553ac.js:1:621316)
    at HTMLAnchorElement.<anonymous> (main.46c4670f1ad553ac.js:1:708822)
    at v.invokeTask (polyfills.6a4fafe69005f56d.js:1:7191)
    at Object.onInvokeTask (main.46c4670f1ad553ac.js:1:649384)
    at v.invokeTask (polyfills.6a4fafe69005f56d.js:1:7112)
    at M.runTask (polyfills.6a4fafe69005f56d.js:1:2556)
    at m.invokeTask [as invoke] (polyfills.6a4fafe69005f56d.js:1:8242)
```

**Comment by linaori** [comment]
Update "view on curse" for example works in the popup, but the right click context menu in the addon list for that same link does not
