### ISSUE TITLE
WowUp 2.10.0 AppImage not drawing correctly

### ISSUE THREAD

**Issue by tankersss** [WowUp/WowUp#1461]
**Describe the bug**
UI is not drawing correctly, I can press buttons/links if I know where they are, and some are highlighted.

**To Reproduce**
1. run WowUp-2.10.0.AppImage
2. See error in Log

**Expected behavior**
It should just work

**Screenshots**
![Screenshot_20240122_115534](https://github.com/WowUp/WowUp/assets/34248843/b5b73a80-f416-47f0-9312-329054ae7fcf)

**Desktop (please complete the following information):**
 - OS: Nubara Linux 39
 - Browser: Chrome
 - Version: 120.0.6099.224

**Additional context**
It worked 2-3 times before breaking.
After some digging I deleted everything in ~/.config/WowUp/GPUCache and it's working fine now, I believe it's an Electron Bug due to shader errors. 
Altho I still get some error when closing the app 
`[wago-handler] clearing reload timer
[93866:0122/120424.349004:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[93866:0122/120424.364553:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
12:04:25.534 › window config saved
`  
[WowupLog.txt](https://github.com/WowUp/WowUp/files/14009392/WowupLog.txt)

**Comment by zikziko** [comment]
I'm facing same issues NixOS 23.11 works fine after deleting files in ~/.config/WowUp/GPUCache

**Comment by Thulium-Drake** [comment]
Didn't fix the issue with 2.11.0 for me, it starts up, shows all the stuff normally. But when the window loses focus, it turns all gray again...

```
23:58:51.644 › Main starting
23:58:51.647 › Electron: 26.2.0
23:58:51.647 › BinaryPath: /tmp/.mount_WowUp-7ichw5/wowup-cf
23:58:51.647 › ExecPath /tmp/.mount_WowUp-7ichw5/wowup-cf
23:58:51.647 › Args [ '/tmp/.mount_WowUp-7ichw5/wowup-cf' ]
23:58:51.647 › Log path: /home/jeff/.config/WowUpCf/logs
23:58:51.648 › File does not exist: /home/jeff/.config/WowUpCf/GPUCache
23:58:51.648 › ENOENT: no such file or directory, access '/home/jeff/.config/WowUpCf/GPUCache'
23:58:51.648 › ARGV { _: [], serve: false, hidden: false }
23:58:51.649 › USER_AGENT WowUp-Client/2.11.0 (Linux; 6.1.0-17-amd64; x64; CF;  +https://wowup.io)
23:58:51.654 › Hardware acceleration enabled
23:58:51.893 › App ready: 245ms
23:58:51.940 › process.versions {
  node: '18.16.1',
  acorn: '8.8.2',
  ada: '1.0.4',
  ares: '1.19.1',
  brotli: '1.0.9',
  cldr: '43.0',
  icu: '73.1',
  llhttp: '6.0.11',
  modules: '116',
  napi: '8',
  nghttp2: '1.52.0',
  openssl: '1.1.1',
  simdutf: '3.2.2',
  tz: '2023c',
  undici: '5.21.0',
  unicode: '15.0',
  uv: '1.44.2',
  uvwasi: '0.0.15',
  v8: '11.6.189.20-electron.0',
  zlib: '1.2.13.1-motley',
  electron: '26.2.0',
  chrome: '116.0.5845.179'
}
23:58:51.941 › Loading app URL: 293ms
START_WITH_SYSTEM_PREFERENCE_KEY: undefined
START_MINIMIZED_PREFERENCE_KEY: undefined
23:58:52.346 › Checking for update
23:58:52.347 › autoUpdater checking-for-update
23:58:52.561 › Platform linux true
23:58:52.562 › [CreateDirectory] '/home/jeff/.config/WowUpCf/downloads'
23:58:52.571 › Language setup start
23:58:52.572 › getStartMinimized undefined null
23:58:52.574 › Set Language Preference: en
23:58:52.578 › loginItemSettings { __zone_symbol__state: null, __zone_symbol__value: [] }
23:58:52.579 › [GET] ./assets/i18n/en.json 200 5ms
23:58:52.591 › using locale en
23:58:52.599 › Language setup complete
23:58:52.601 › Failed to search for Lutris library location Error
    at file:///tmp/.mount_WowUp-7ichw5/resources/app.asar/dist/main.f421da7cf63015b0.js:1:1328809
    at Generator.next (<anonymous>)
    at MK (file:///tmp/.mount_WowUp-7ichw5/resources/app.asar/dist/main.f421da7cf63015b0.js:1:737613)
    at a (file:///tmp/.mount_WowUp-7ichw5/resources/app.asar/dist/main.f421da7cf63015b0.js:1:737816)
    at v.invoke (file:///tmp/.mount_WowUp-7ichw5/resources/app.asar/dist/polyfills.74362bc7c9f71f5d.js:1:6583)
    at Object.onInvoke (file:///tmp/.mount_WowUp-7ichw5/resources/app.asar/dist/main.f421da7cf63015b0.js:1:634704)
    at v.invoke (file:///tmp/.mount_WowUp-7ichw5/resources/app.asar/dist/polyfills.74362bc7c9f71f5d.js:1:6523)
    at L.run (file:///tmp/.mount_WowUp-7ichw5/resources/app.asar/dist/polyfills.74362bc7c9f71f5d.js:1:1964)
    at file:///tmp/.mount_WowUp-7ichw5/resources/app.asar/dist/polyfills.74362bc7c9f71f5d.js:1:16722
    at v.invokeTask (file:///tmp/.mount_WowUp-7ichw5/resources/app.asar/dist/polyfills.74362bc7c9f71f5d.js:1:7201)
23:58:52.601 › Failed to search for blizzard products Error: Lutris library not found
    at file:///tmp/.mount_WowUp-7ichw5/resources/app.asar/dist/main.f421da7cf63015b0.js:1:1327700
    at Generator.next (<anonymous>)
    at MK (file:///tmp/.mount_WowUp-7ichw5/resources/app.asar/dist/main.f421da7cf63015b0.js:1:737613)
    at a (file:///tmp/.mount_WowUp-7ichw5/resources/app.asar/dist/main.f421da7cf63015b0.js:1:737816)
    at v.invoke (file:///tmp/.mount_WowUp-7ichw5/resources/app.asar/dist/polyfills.74362bc7c9f71f5d.js:1:6583)
    at Object.onInvoke (file:///tmp/.mount_WowUp-7ichw5/resources/app.asar/dist/main.f421da7cf63015b0.js:1:634704)
    at v.invoke (file:///tmp/.mount_WowUp-7ichw5/resources/app.asar/dist/polyfills.74362bc7c9f71f5d.js:1:6523)
    at L.run (file:///tmp/.mount_WowUp-7ichw5/resources/app.asar/dist/polyfills.74362bc7c9f71f5d.js:1:1964)
    at file:///tmp/.mount_WowUp-7ichw5/resources/app.asar/dist/polyfills.74362bc7c9f71f5d.js:1:16722
    at v.invokeTask (file:///tmp/.mount_WowUp-7ichw5/resources/app.asar/dist/polyfills.74362bc7c9f71f5d.js:1:7201)
23:58:52.609 › Cannot import wow installations, no agent path
23:58:52.614 › WowUpProtocolService 
23:58:52.618 › Creating app menu
23:58:52.625 › onAutoUpdateInterval
23:58:52.636 › zoomPref null
23:58:52.637 › App menu created true
23:58:52.637 › Creating tray
Creating tray
23:58:52.644 › Tray created true
23:58:52.660 › Set Language Preference: en
IPC_OW_IS_CMP_REQUIRED failed TypeError: Cannot read properties of undefined (reading 'isCMPRequired')
    at /tmp/.mount_WowUp-7ichw5/resources/app.asar/app/ipc-events.js:104:50
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:89468)
    at WebContents.emit (node:events:513:28)
23:58:52.873 › Checking for addon updates...
23:58:52.923 › AG Grid: Since v31, 'columnApi.applyColumnState' is deprecated and moved to 'api.applyColumnState'.
23:58:52.933 › getCollapseToTray true
23:58:52.935 › Set Language Preference: en
23:58:52.938 › getStartMinimized undefined null
23:58:52.948 › AG Grid: Since v31, 'columnApi.getColumnState' is deprecated and moved to 'api.getColumnState'.
23:58:52.964 › AG Grid: setRowData is deprecated. Please use 'api.setGridOption('rowData', newValue)' or 'api.updateGridOptions({ rowData: newValue })' instead.
23:58:53.021 › AG Grid: Since v31, 'columnApi.autoSizeColumns' is deprecated and moved to 'api.autoSizeColumns'.
23:58:53.084 › Update for version 2.11.0 is not available (latest version: 2.11.0, downgrade is disallowed).
23:58:53.084 › autoUpdater update-not-available {
  tag: 'v2.11.0',
  version: '2.11.0',
  files: [
    {
      url: 'WowUp-CF-2.11.0.AppImage',
      sha512: 'zM+FkgE6M70PHkJVpup2zDbDZZ6q6hYsP+y2eRIk8eOrZ/PVsnyheDAJQjqrO0k7zA60hQojlmXbykvVwpTATw==',
      size: 120553003,
      blockMapSize: 126527
    }
  ],
  path: 'WowUp-CF-2.11.0.AppImage',
  sha512: 'zM+FkgE6M70PHkJVpup2zDbDZZ6q6hYsP+y2eRIk8eOrZ/PVsnyheDAJQjqrO0k7zA60hQojlmXbykvVwpTATw==',
  releaseDate: '2024-02-05T17:09:55.424Z',
  releaseName: '2.11.0',
  releaseNotes: '<p>Lots of changes</p>'
}
23:58:53.085 › checkForUpdates {
  versionInfo: {
    tag: 'v2.11.0',
    version: '2.11.0',
    files: [ [Object] ],
    path: 'WowUp-CF-2.11.0.AppImage',
    sha512: 'zM+FkgE6M70PHkJVpup2zDbDZZ6q6hYsP+y2eRIk8eOrZ/PVsnyheDAJQjqrO0k7zA60hQojlmXbykvVwpTATw==',
    releaseDate: '2024-02-05T17:09:55.424Z',
    releaseName: '2.11.0',
    releaseNotes: '<p>Lots of changes</p>'
  },
  updateInfo: {
    tag: 'v2.11.0',
    version: '2.11.0',
    files: [ [Object] ],
    path: 'WowUp-CF-2.11.0.AppImage',
    sha512: 'zM+FkgE6M70PHkJVpup2zDbDZZ6q6hYsP+y2eRIk8eOrZ/PVsnyheDAJQjqrO0k7zA60hQojlmXbykvVwpTATw==',
    releaseDate: '2024-02-05T17:09:55.424Z',
    releaseName: '2.11.0',
    releaseNotes: '<p>Lots of changes</p>'
  }
}
23:58:53.085 › IPC_APP_UPDATE_STATE app-update-state
23:58:53.085 › { state: 3 }
23:58:53.228 › [POST] https://hub.wowup.io/addons/batch 200 582ms
23:58:53.609 › Checking for addon updates...
23:58:59.707 › webContents render-process-gone
23:58:59.708 › { reason: 'crashed', exitCode: 11 }
23:58:59.708 › Restarting main window
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94495)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at BrowserWindow.<anonymous> (/tmp/.mount_WowUp-7ichw5/resources/app.asar/app/main.js:260:67)
    at BrowserWindow.emit (node:events:525:35)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94495)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at BrowserWindow.<anonymous> (/tmp/.mount_WowUp-7ichw5/resources/app.asar/app/main.js:257:67)
    at BrowserWindow.emit (node:events:525:35)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94495)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at BrowserWindow.<anonymous> (/tmp/.mount_WowUp-7ichw5/resources/app.asar/app/main.js:260:67)
    at BrowserWindow.emit (node:events:525:35)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94495)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at BrowserWindow.<anonymous> (/tmp/.mount_WowUp-7ichw5/resources/app.asar/app/main.js:257:67)
    at BrowserWindow.emit (node:events:525:35)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94495)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at BrowserWindow.<anonymous> (/tmp/.mount_WowUp-7ichw5/resources/app.asar/app/main.js:260:67)
    at BrowserWindow.emit (node:events:525:35)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94495)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at BrowserWindow.<anonymous> (/tmp/.mount_WowUp-7ichw5/resources/app.asar/app/main.js:257:67)
    at BrowserWindow.emit (node:events:525:35)

```

**Comment by marco-kretz** [comment]
Same issue here on Pop!_OS 22.04 with NVIDIA. Glad to help if you need any informtion.

**Comment by WarcraftSimp** [comment]
same problem, deleting the GPUcache folder does not help at all. 

./WowUp-CF-2.11.0_0ac2d7ef18bf372ce304fc80a075fd9c.AppImage
12:57:38.123 › Main starting
12:57:38.126 › Electron: 26.2.0
12:57:38.126 › BinaryPath: /tmp/.mount_WowUp-Vetzds/wowup-cf
12:57:38.126 › ExecPath /tmp/.mount_WowUp-Vetzds/wowup-cf
12:57:38.127 › Args [ '/tmp/.mount_WowUp-Vetzds/wowup-cf' ]
12:57:38.127 › Log path: /home/onyxia/.config/WowUpCf/logs
12:57:38.128 › ARGV { _: [], serve: false, hidden: false }
12:57:38.128 › USER_AGENT WowUp-Client/2.11.0 (Linux; 6.5.0-17-generic; x64; CF;  +https://wowup.io)
12:57:38.137 › Hardware acceleration enabled
12:57:38.413 › App ready: 286ms
12:57:38.456 › process.versions {
  node: '18.16.1',
  acorn: '8.8.2',
  ada: '1.0.4',
  ares: '1.19.1',
  brotli: '1.0.9',
  cldr: '43.0',
  icu: '73.1',
  llhttp: '6.0.11',
  modules: '116',
  napi: '8',
  nghttp2: '1.52.0',
  openssl: '1.1.1',
  simdutf: '3.2.2',
  tz: '2023c',
  undici: '5.21.0',
  unicode: '15.0',
  uv: '1.44.2',
  uvwasi: '0.0.15',
  v8: '11.6.189.20-electron.0',
  zlib: '1.2.13.1-motley',
  electron: '26.2.0',
  chrome: '116.0.5845.179'
}
12:57:38.457 › Loading app URL: 330ms
12:57:38.490 › Error: ERR_FAILED (-2) loading 'file:///tmp/.mount_WowUp-Vetzds/resources/app.asar/dist/index.html'
    at rejectAndCleanup (node:electron/js2c/browser_init:2:85371)
    at WebContents.stopLoadingListener (node:electron/js2c/browser_init:2:85758)
    at WebContents.emit (node:events:513:28)

**Comment by loissascha** [comment]
Same issue with WowUp-CF-2.11.0.AppImage on Nobara 39. 
The above mentioned fix didn't work. 
It shows fine until the window gets focus, then it throws an error message in the terminal and the whole window just shows in one color. 

This is the error message I get when this happens: 
`13:25:00.885 › webContents render-process-gone
13:25:00.885 › { reason: 'crashed', exitCode: 139 }
13:25:00.885 › Restarting main window
[40576:0225/132500.887764:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
13:25:03.788 › window config saved`

**Comment by Thulium-Drake** [comment]
Fixed with 2.11.1!
