### ISSUE TITLE
Appimage closes on launch

### ISSUE THREAD

**Issue by peoii** [WowUp/WowUp#1474]
**Describe the bug**
Upon launching the appimage on my archlinux install, it immediately closes.

**To Reproduce**
1. Run WowUp.appImage

**Expected behavior**
I'd mostly just like the application to launch.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser firefox
 - Version 2.12

**Additional context**
Logs produce very little information:

[2024-05-07 18:05:19.558] [info]  Main starting
[2024-05-07 18:05:19.561] [info]  Electron: 30.0.2
[2024-05-07 18:05:19.562] [info]  BinaryPath: /tmp/.mount_WowUp-9a3IYP/wowup
[2024-05-07 18:05:19.562] [info]  ExecPath /tmp/.mount_WowUp-9a3IYP/wowup
[2024-05-07 18:05:19.562] [info]  Args [ '/tmp/.mount_WowUp-9a3IYP/wowup' ]
[2024-05-07 18:05:19.564] [info]  Log path: /home/peoii/.config/WowUp/logs
[2024-05-07 18:05:19.565] [info]  ARGV { _: [], serve: false, hidden: false }
[2024-05-07 18:05:19.565] [info]  USER_AGENT WowUp-Client/2.12.0 (Linux; 6.8.8-arch1-1; x64;  +https://wowup.io)
[2024-05-07 18:05:19.591] [info]  Hardware acceleration enabled
[2024-05-07 18:05:19.934] [info]  App ready: 370ms
[2024-05-07 18:05:20.062] [info]  process.versions {
  node: '20.11.1',
  acorn: '8.11.2',
  ada: '2.7.4',
  ares: '1.20.1',
  base64: '0.5.1',
  brotli: '1.0.9',
  cjs_module_lexer: '1.2.2',
  cldr: '43.0',
  icu: '73.1',
  llhttp: '8.1.1',
  modules: '123',
  napi: '9',
  nghttp2: '1.58.0',
  openssl: '1.1.1',
  simdutf: '4.0.4',
  tz: '2024a',
  undici: '5.28.3',
  unicode: '15.0',
  uv: '1.46.0',
  uvwasi: '0.0.19',
  v8: '12.4.254.14-electron.0',
  zlib: '1.2.13.1-motley-5daffc7',
  electron: '30.0.2',
  chrome: '124.0.6367.91'
}
[2024-05-07 18:05:20.063] [info]  Loading app URL: 499ms
[2024-05-07 18:05:20.244] [info]  window config saved

**Comment by peoii** [comment]
Of interesting note, WowUp-CF on version 2.12 launches fine, it's just the non-CF version.

**Comment by jliddev** [comment]
the current appimage appears to work fine on my fedora install. Is there any extra output if you run it in the console? system crash log? 

![image](https://github.com/WowUp/WowUp/assets/20467484/b800e979-1928-489a-a376-bc71c684722c)

**Comment by jliddev** [comment]
I wonder if you edit ~/.config/WowUp/preferences.json and set use_hardware_acceleration to "false"

**Comment by drotter120** [comment]
I had the same problem, and logs were practically identical to the original reporter.

I tried editing ~/.config/WowUp/preferences.json and set use_hardware_acceleration to "false" edit ~/.config/WowUp/preferences.json and set use_hardware_acceleration to "false", and removing the GPUCache folder, but it didn't help.

However, completely removing ~/.config/WowUp does seem to have fixed it for me.

**Comment by jliddev** [comment]
sounds like some kind of cached electron thing

**Comment by Prejudice182** [comment]
I believe it is something to do with having the window fullscreen.
When I removed ~/.config/WowUp, it launched no problem, and the window was not fullscreen.
When I tried to make it fullscreen, it crashed, and continues to do so on launch.
`prejudice182@pop-os:~/Downloads$ ./WowUp-2.12.0.AppImage 
10:49:28.274 › Main starting
10:49:28.277 › Electron: 30.0.2
10:49:28.278 › BinaryPath: /tmp/.mount_WowUp-kKvBEi/wowup
10:49:28.278 › ExecPath /tmp/.mount_WowUp-kKvBEi/wowup
10:49:28.278 › Args [ '/tmp/.mount_WowUp-kKvBEi/wowup' ]
10:49:28.280 › Log path: /home/prejudice182/.config/WowUp/logs
10:49:28.281 › ARGV { _: [], serve: false, hidden: false }
10:49:28.281 › USER_AGENT WowUp-Client/2.12.0 (Linux; 6.8.0-76060800daily20240311-generic; x64;  +https://wowup.io)
10:49:28.291 › Hardware acceleration enabled
10:49:28.669 › App ready: 389ms
10:49:28.830 › process.versions {
  node: '20.11.1',
  acorn: '8.11.2',
  ada: '2.7.4',
  ares: '1.20.1',
  base64: '0.5.1',
  brotli: '1.0.9',
  cjs_module_lexer: '1.2.2',
  cldr: '43.0',
  icu: '73.1',
  llhttp: '8.1.1',
  modules: '123',
  napi: '9',
  nghttp2: '1.58.0',
  openssl: '1.1.1',
  simdutf: '4.0.4',
  tz: '2024a',
  undici: '5.28.3',
  unicode: '15.0',
  uv: '1.46.0',
  uvwasi: '0.0.19',
  v8: '12.4.254.14-electron.0',
  zlib: '1.2.13.1-motley-5daffc7',
  electron: '30.0.2',
  chrome: '124.0.6367.91'
}
10:49:28.831 › Loading app URL: 551ms
10:49:29.017 › window config saved
Segmentation fault (core dumped)
`

**Comment by CyanoHao** [comment]
Same on Arch Linux, built against system electron (electron30 30.0.1-2).

It works after I removed Dragonflight entry from `~/.config/WowUp/preferences.json`.

Backtrace:
```
Thread 1 "electron" received signal SIGSEGV, Segmentation fault.
0x000055555c202afd in views::View::UpdateChildLayerBounds(views::View::LayerOffsetData const&) ()
(gdb) bt
#0  0x000055555c202afd in views::View::UpdateChildLayerBounds(views::View::LayerOffsetData const&) ()
#1  0x000055555c202aef in views::View::UpdateChildLayerBounds(views::View::LayerOffsetData const&) ()
#2  0x000055555c202aef in views::View::UpdateChildLayerBounds(views::View::LayerOffsetData const&) ()
#3  0x000055555c202aef in views::View::UpdateChildLayerBounds(views::View::LayerOffsetData const&) ()
#4  0x000055555c202aef in views::View::UpdateChildLayerBounds(views::View::LayerOffsetData const&) ()
#5  0x000055555c202aef in views::View::UpdateChildLayerBounds(views::View::LayerOffsetData const&) ()
#6  0x000055555c202aef in views::View::UpdateChildLayerBounds(views::View::LayerOffsetData const&) ()
#7  0x000055555c202aef in views::View::UpdateChildLayerBounds(views::View::LayerOffsetData const&) ()
#8  0x000055555c202aef in views::View::UpdateChildLayerBounds(views::View::LayerOffsetData const&) ()
#9  0x000055555c201a1e in views::View::SetBoundsRect(gfx::Rect const&) ()
#10 0x000055555c202dc4 in views::View::SetSize(gfx::Size const&) ()
#11 0x000055555c221cb9 in views::Widget::OnNativeWidgetSizeChanged(gfx::Size const&) ()
#12 0x000055555c254658 in non-virtual thunk to views::DesktopNativeWidgetAura::OnHostResized(aura::WindowTreeHost*)
    ()
#13 0x000055555c080e92 in aura::WindowTreeHost::OnHostResizedInPixels(gfx::Size const&) ()
#14 0x000055555c082f18 in aura::WindowTreeHostPlatform::OnBoundsChanged(ui::PlatformWindowDelegate::BoundsChange const&) ()
#15 0x0000555556e50aef in electron::ElectronDesktopWindowTreeHostLinux::OnBoundsChanged(ui::PlatformWindowDelegate::BoundsChange const&) ()
#16 0x000055555780aab8 in ui::X11Window::DelayedResize(bool) ()
#17 0x000055555705acb9 in void base::internal::CancelableCallbackImpl<base::OnceCallback<void ()> >::ForwardOnce<>() ()
#18 0x000055555a7ddbbe in base::TaskAnnotator::RunTaskImpl(base::PendingTask&) ()
#19 0x000055555a7f661c in base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*) ()
#20 0x000055555a7f6001 in base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() ()
#21 0x000055555a7f6d75 in non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() ()
#22 0x000055555a85de72 in base::MessagePumpGlib::Run(base::MessagePump::Delegate*) ()
#23 0x000055555a7f7143 in base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) ()
#24 0x000055555a7c34be in base::RunLoop::Run(base::Location const&) ()
#25 0x000055555960d25d in content::BrowserMainLoop::RunMainMessageLoop() ()
#26 0x000055555960f0e3 in content::BrowserMainRunnerImpl::Run() ()
#27 0x000055555960a70c in content::BrowserMain(content::MainFunctionParams) ()
#28 0x0000555556fbe8c7 in content::RunBrowserProcessMain(content::MainFunctionParams, content::ContentMainDelegate*) ()
#29 0x0000555556fc02c2 in content::ContentMainRunnerImpl::RunBrowser(content::MainFunctionParams, bool) ()
#30 0x0000555556fc00b9 in content::ContentMainRunnerImpl::Run() ()
#31 0x0000555556fbd3d1 in content::RunContentProcess(content::ContentMainParams, content::ContentMainRunner*) ()
#32 0x0000555556fbd8ca in content::ContentMain(content::ContentMainParams) ()
#33 0x0000555556c680be in main ()
```

**Comment by CyanoHao** [comment]
I tried downgrading electron to 29 and now it works.
https://aur.archlinux.org/cgit/aur.git/commit/?h=wowup-native&id=163daa9a2dfd1bbc5d038605fe3bd7f9a4f6161a

Maybe it's an upstream regression.

**Comment by bitterwinter8232** [comment]
I managed to fix this by editing the preferences.json file and changing the main-window-is-maximised variable to false. However as others have mentioned in this thread changing it to fullscreen does crash it. I'm running Mint 21.3.
