### ISSUE TITLE
Cant change provider of DBM to Curse

### ISSUE THREAD

**Issue by Addonman** [WowUp/WowUp#586]
**Describe the bug**
I wanted to change provider from wowinteface to CF but giving error"Failed to change provider for DBM to Curse"
**To Reproduce**
Use WOWup try to change provider
**Expected behavior**
Change of provider
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] win10
 - Browser [e.g. chrome, safari] firefox
 - Version [e.g. 22] 2.0.2

**Additional context**

**Comment by linaori** [comment]
Do you have any logs to see what's going wrong?

**Comment by Addonman** [comment]
I cleared all logs from before and tried again so i get some new logs
This is from renedrer log file
[2020-12-11 21:02:11.443] [error] Error: ERROR_ADDON_ALREADY_INSTALLED
    at t.<anonymous> (file:///C:/Users/Korisnik/AppData/Local/Programs/wowup/resources/app.asar/dist/main-es2015.5cba289c02b5b27d0ae4.js:1:1174982)
    at Generator.next (<anonymous>)
    at file:///C:/Users/Korisnik/AppData/Local/Programs/wowup/resources/app.asar/dist/main-es2015.5cba289c02b5b27d0ae4.js:1:1162843
    at new D (file:///C:/Users/Korisnik/AppData/Local/Programs/wowup/resources/app.asar/dist/polyfills-es2015.0dd68a3f76e24363f2e7.js:1:14037)
    at Yk (file:///C:/Users/Korisnik/AppData/Local/Programs/wowup/resources/app.asar/dist/main-es2015.5cba289c02b5b27d0ae4.js:1:1162588)
    at t.setProvider (file:///C:/Users/Korisnik/AppData/Local/Programs/wowup/resources/app.asar/dist/main-es2015.5cba289c02b5b27d0ae4.js:1:1174850)
    at t.<anonymous> (file:///C:/Users/Korisnik/AppData/Local/Programs/wowup/resources/app.asar/dist/main-es2015.5cba289c02b5b27d0ae4.js:1:1598082)
    at Generator.next (<anonymous>)
    at file:///C:/Users/Korisnik/AppData/Local/Programs/wowup/resources/app.asar/dist/main-es2015.5cba289c02b5b27d0ae4.js:1:1573592
    at new D (file:///C:/Users/Korisnik/AppData/Local/Programs/wowup/resources/app.asar/dist/polyfills-es2015.0dd68a3f76e24363f2e7.js:1:14037)
[2020-12-11 21:02:18.310] [error] Error: ERROR_ADDON_ALREADY_INSTALLED
    at t.<anonymous> (file:///C:/Users/Korisnik/AppData/Local/Programs/wowup/resources/app.asar/dist/main-es2015.5cba289c02b5b27d0ae4.js:1:1174982)
    at Generator.next (<anonymous>)
    at file:///C:/Users/Korisnik/AppData/Local/Programs/wowup/resources/app.asar/dist/main-es2015.5cba289c02b5b27d0ae4.js:1:1162843
    at new D (file:///C:/Users/Korisnik/AppData/Local/Programs/wowup/resources/app.asar/dist/polyfills-es2015.0dd68a3f76e24363f2e7.js:1:14037)
    at Yk (file:///C:/Users/Korisnik/AppData/Local/Programs/wowup/resources/app.asar/dist/main-es2015.5cba289c02b5b27d0ae4.js:1:1162588)
    at t.setProvider (file:///C:/Users/Korisnik/AppData/Local/Programs/wowup/resources/app.asar/dist/main-es2015.5cba289c02b5b27d0ae4.js:1:1174850)
    at t.<anonymous> (file:///C:/Users/Korisnik/AppData/Local/Programs/wowup/resources/app.asar/dist/main-es2015.5cba289c02b5b27d0ae4.js:1:1598082)
    at Generator.next (<anonymous>)
    at file:///C:/Users/Korisnik/AppData/Local/Programs/wowup/resources/app.asar/dist/main-es2015.5cba289c02b5b27d0ae4.js:1:1573592
    at new D (file:///C:/Users/Korisnik/AppData/Local/Programs/wowup/resources/app.asar/dist/polyfills-es2015.0dd68a3f76e24363f2e7.js:1:14037)

Maybe problem is that Wowup see 2 DBM addons -i get both versions in list -1 from Curse (new alpha version) and 1 from Wowinterface (older version-not sure if author posts alpha versions there at all)

**Comment by jliddev** [comment]
yeah if you have two of the same addon installed, it wont let you change it cause they collide.

**Comment by Addonman** [comment]
You understood me incorrectly-i have 1 installed addons (alpha from CF),but gives me 2 version to update -1 from Curseforge and 1 from Wowinterface. I update from CF and still have WOWup saying that i need to update to no much oldrer version from WI.

After rescaning folder now evrything is correct.
