### ISSUE TITLE
Addon Folder Missing After Update

### ISSUE THREAD

**Issue by DHumphrey** [WowUp/WowUp#739]
Last night I noticed that DBM (Core) was no longer working or installed. It still showed as installed in WowUp, but the folder was no longer present. I had to do a reinstall through WowUp. Looking through logs it looks like this has happened with other addons as well, such as Leatrix.

It seems like there was a problem downloading or extracting the addon zip. However, WowUp backed up and deleted the original addon folder. After the unzip failure the backup is not restored, leaving the addon missing/unusable.

**Version:** 2.1.2
**OS:** Windows 10

**Reproduction steps:**
1) Have addon installed
2) Configure addon for Auto-Update (not sure if related)
3) Addon gets updated
4) Addon is no longer present in Interfaces folder

`[2021-02-18 08:08:26.690] [info] Ensure existing backup is deleted C:\Program Files (x86)\World of Warcraft\_retail_\Interface\AddOns\Leatrix_Plus-bak
[2021-02-18 08:08:26.692] [info] Backing up C:\Program Files (x86)\World of Warcraft\_retail_\Interface\AddOns\Leatrix_Plus
[2021-02-18 08:08:26.725] [info] unzipFile C:\Users\username\AppData\Roaming\WowUp\downloads\leatrix-plus-shadowlands.zip
[2021-02-18 08:08:26.787] [info] Ensure existing backup is deleted C:\Program Files (x86)\World of Warcraft\_retail_\Interface\AddOns\Leatrix_Plus-bak
[2021-02-18 08:08:26.890] [info] Ensure existing backup is deleted C:\Program Files (x86)\World of Warcraft\_retail_\Interface\AddOns\Leatrix_Plus-bak
[2021-02-18 08:08:26.891] [info] Removing backup C:\Program Files (x86)\World of Warcraft\_retail_\Interface\AddOns\Leatrix_Plus-bak
[2021-02-18 08:08:26.891] [info] Backing up C:\Program Files (x86)\World of Warcraft\_retail_\Interface\AddOns\Leatrix_Plus
[2021-02-18 08:08:26.894] [info] Backing up C:\Program Files (x86)\World of Warcraft\_retail_\Interface\AddOns\Leatrix_Plus
[2021-02-18 08:08:26.896] [info] Addon added new directories []
[2021-02-18 08:08:26.915] [info] Leatrix Plus (Shadowlands): No dependencies found
[2021-02-18 08:08:27.124] [info] unzipFile C:\Users\username\AppData\Roaming\WowUp\downloads\leatrix-plus-shadowlands.zip
[2021-02-18 08:08:27.186] [info] unzipFile C:\Users\username\AppData\Roaming\WowUp\downloads\leatrix-plus-shadowlands.zip
[2021-02-18 08:08:27.191] [info] Install complete Leatrix Plus (Shadowlands)
[2021-02-18 08:08:27.225] [info] Removing backup C:\Program Files (x86)\World of Warcraft\_retail_\Interface\AddOns\Leatrix_Plus-bak
[2021-02-18 08:08:27.236] [info] Addon added new directories []
[2021-02-18 08:08:27.257] [info] Leatrix Plus (Shadowlands): No dependencies found
[2021-02-18 08:08:27.355] [info] Removing backup C:\Program Files (x86)\World of Warcraft\_retail_\Interface\AddOns\Leatrix_Plus-bak
[2021-02-18 08:08:27.356] [info] Addon added new directories []
[2021-02-18 08:08:27.367] [info] Leatrix Plus (Shadowlands): No dependencies found
[2021-02-18 08:08:27.465] [info] Install complete Leatrix Plus (Shadowlands)
[2021-02-18 08:08:27.622] [info] Ensure existing backup is deleted C:\Program Files (x86)\World of Warcraft\_retail_\Interface\AddOns\Leatrix_Plus-bak
[2021-02-18 08:08:27.624] [info] Backing up C:\Program Files (x86)\World of Warcraft\_retail_\Interface\AddOns\Leatrix_Plus
[2021-02-18 08:08:27.627] [info] Install complete Leatrix Plus (Shadowlands)
[2021-02-18 08:08:27.735] [info] unzipFile C:\Users\username\AppData\Roaming\WowUp\downloads\leatrix-plus-shadowlands.zip
[2021-02-18 08:08:27.738] [error] Error: Error invoking remote method 'unzip-file': Error: Invalid filename
    at EventEmitter.o.invoke (electron/js2c/renderer_init.js:71:535)
[2021-02-18 08:08:27.753] [error] Error: Error invoking remote method 'unzip-file': Error: Invalid filename
    at EventEmitter.o.invoke (electron/js2c/renderer_init.js:71:535)
[2021-02-18 08:08:27.844] [info] Install complete Leatrix Plus (Shadowlands)`
[renderer.log](https://github.com/WowUp/WowUp/files/6010527/renderer.log)

**Comment by jliddev** [comment]
I believe this is the log we looked at where the auto update loop was running twice in parallel, which is an issue to be looked at.

**Comment by DHumphrey** [comment]
Not sure if it helps, but after restarting WowUp on the 19th, I noticed that the UndermineJournal addon tried to update and got deleted on the 20th, and the RaiderIO addon update failed on the 23rd, also deleting the directory.

[2021-02-20 09:16:46.508] [info] unzipFile C:\Users\user\AppData\Roaming\WowUp\downloads\the-undermine-journal.zip
[2021-02-20 09:16:46.511] [error] Error: Error invoking remote method 'unzip-file': Error: Invalid filename
    at EventEmitter.o.invoke (electron/js2c/renderer_init.js:71:535)
[2021-02-20 09:16:46.527] [error] Error: Error invoking remote method 'unzip-file': Error: Invalid filename
    at EventEmitter.o.invoke (electron/js2c/renderer_init.js:71:535)

[2021-02-23 08:13:07.727] [info] unzipFile C:\Users\user\AppData\Roaming\WowUp\downloads\raiderio-mythic-plus-and-raid-progress.zip
[2021-02-23 08:13:10.515] [info] Addon added new directories []
[2021-02-23 08:13:10.564] [info] Raider.IO Mythic Plus and Raid Progress: No dependencies found
[2021-02-23 08:13:10.684] [error] Failed to copy addon directory C:\Program Files (x86)\World of Warcraft\_retail_\Interface\AddOns\RaiderIO_DB_EU_A
[2021-02-23 08:13:10.686] [error] Error: Error invoking remote method 'copy-file': Error: ENOENT: no such file or directory, unlink 'C:\Program Files (x86)\World of Warcraft\_retail_\Interface\AddOns\RaiderIO_DB_EU_A\RaiderIO_DB_EU_A.toc'
    at EventEmitter.o.invoke (electron/js2c/renderer_init.js:71:535)
[renderer.log](https://github.com/WowUp/WowUp/files/6038976/renderer.log)

**Comment by jliddev** [comment]
Changes were made in the latest beta to attempt to prevent multiple update loops from happening
