### ISSUE TITLE
Angular failed to delete output dir in clean build process

### ISSUE THREAD

**Issue by CyanoHao** [WowUp/WowUp#975]
**Describe the bug**
Doing a clean build from v2.4.2 source code, I received this error message:
```
> wowup@2.4.2 build:prod
> npm run build -- -c production


> wowup@2.4.2 build
> npm run electron:serve-tsc && ng build --base-href ./ "-c" "production"


> wowup@2.4.2 electron:serve-tsc
> tsc -p tsconfig.serve.json

⠋ Generating browser application bundles (phase: setup)...An unhandled exception occurred: ENOENT: no such file or directory, stat '/home/cyano/aur-wowup/WowUp-2.4.2/wowup-electron/dist'
See "/tmp/ng-nsQX3R/angular-errors.log" for further details.
```
The error log file:
```
[error] Error: ENOENT: no such file or directory, stat '/home/cyano/aur-wowup/WowUp-2.4.2/wowup-electron/dist'
    at Object.statSync (node:fs:1526:3)
    at __node_internal_ (node:internal/fs/utils:767:8)
    at Object.rmdirSync (node:fs:1146:15)
    at Object.deleteOutputDir (/home/cyano/aur-wowup/WowUp-2.4.2/wowup-electron/node_modules/@angular-devkit/build-angular/src/utils/delete-output-dir.js:21:10)
    at initialize (/home/cyano/aur-wowup/WowUp-2.4.2/wowup-electron/node_modules/@angular-devkit/build-angular/src/browser/index.js:86:17)
    at async SwitchMapSubscriber.project (/home/cyano/aur-wowup/WowUp-2.4.2/wowup-electron/node_modules/@angular-devkit/build-angular/src/browser/index.js:114:17)
```

**To Reproduce**
1. Download v2.4.2 source code (tar.gz) and extract it.
2. In `WowUp-2.4.2/wowup-electron`, run
   ```bash
   npm install
   npm build:prod
   ```

**Expected behavior**
The app is successfully built and can be then packed.

**Screenshots**

**Desktop (please complete the following information):**
- OS: Arch Linux
- node v16.4.0
- npm 7.17.0

**Additional context**
The updated `package-lock.json` file after `npm install`: [package-lock.zip](https://github.com/WowUp/WowUp/files/6729193/package-lock.zip)

**Comment by jliddev** [comment]
You will not be able to pack it without keys this way.

**Comment by jliddev** [comment]
To build an exe locally you want npm run electron:publish:never:local
