### ISSUE TITLE
When backing up \Interface\AddOns folder with Google Drive v49.0.11.0 - Error on addon update: "Error: EPERM: operation not permitted, rmdir"

### ISSUE THREAD

**Issue by nrpieper** [WowUp/WowUp#994]
**Describe the bug**
On Windows 10, when using the Google Drive backup agent v49.0.11.0 and backing up the _retail_\Interface\AddOns folder, the addon update process fails with an error in the renderer.log: 

Error log:
[2021-07-30 14:53:56.314] [info]  [AddonInstall] WowInterface 15749 Threat Plates '10.2.9' -> '10.2.9'
[2021-07-30 14:53:57.038] [error] Invoke failed Error: Error invoking remote method 'delete-directory': Error: EPERM: operation not permitted, rmdir 'C:\Games\World of Warcraft\_retail_\Interface\AddOns\TidyPlates_ThreatPlates-bak\Artwork'
    at EventEmitter.i.invoke (electron/js2c/renderer_init.js:73:529)
[2021-07-30 14:53:57.038] [error] Error: Error invoking remote method 'delete-directory': Error: EPERM: operation not permitted, rmdir 'C:\Games\World of Warcraft\_retail_\Interface\AddOns\TidyPlates_ThreatPlates-bak\Artwork'
    at EventEmitter.i.invoke (electron/js2c/renderer_init.js:73:529)
[2021-07-30 14:53:57.043] [error] Failed to re-install addons Error: Error invoking remote method 'delete-directory': Error: EPERM: operation not permitted, rmdir 'C:\Games\World of Warcraft\_retail_\Interface\AddOns\TidyPlates_ThreatPlates-bak\Artwork'
    at EventEmitter.i.invoke (electron/js2c/renderer_init.js:73:529)

**To Reproduce**
1. Install Google Drive for Desktop (https://support.google.com/drive/answer/7329379#zippy=%2Cdownload-install-google-drive-for-desktop)
2. Configure Google Drive to backup the folder:  <c:\Games\World of Warcraft>\_retail_\Interface\AddOns folder 
2. In the WowUp client try and update any addon, or re-install any addon.
3. The update will fail and the renderer.log file will show the error above.

**Expected behavior**
Without Google Drive configured to backup the Addon's folder, the addon update or re-install process succeeds.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome v92

This issue has been reported to Google through the Google Drive for Desktop feedback button.

**Comment by Raina1007** [comment]
hey, I'm a wowup mod. You will need to do some specific things to resolve this issue.

1. go to your interface/addons folder for the version wow you are having issues with
2. any addons that have -bak as part of will need to be deleted. For example: downloaded DBM, so you should have a DBM folder but if it updates and has issues you would see DBM-bak. Any addon folder that has -bak needs to be deleted. 
3. Once those folders that have - bak deleted, then you will need to install beta. You are having permissions issues that we fixed in the beta. 
4. https://github.com/WowUp/WowUp/releases/tag/v2.5.0-beta.10 
5. you will want to install this one since you are on windows computer - WowUp-Setup-2.5.0-beta.10.exe 
6. You do not need to delete or uninstall the version of wowup you have right now. It is ok to install over it w/ the Beta. Once you download it, go to your download folder and get it installed. 
7. This should fix your addon issue, I can't say for 100% without seeing the renderer log to verify you don't have other issues going on. If there is other addons that don't update, go into ignore status on their own or anything else you can let us know here or hop into our discord and we can try to help you there as well.

**Comment by jliddev** [comment]
Steps were taken to address this in our latest beta if you'd like to give it a try.

**Comment by nrpieper** [comment]
Great, I'll give it a test later today.

**Comment by nrpieper** [comment]
Confirmed that v2.5.0-beta.11 resolves the issue.  Thanks!
